### ISSUE TITLE
mental health assistent (Deep Learning Algorithm)

### ISSUE THREAD

**Issue by ranamanish674zu** [TAHIR0110/ThereForYou#130]
Can you assign it to me? @TAHIR0110 

Full name: Manish Rana
GitHub profile link: https://github.com/ranamanish674zu
Email ID: [manish.rana2021@vitbhopal.ac.in](mailto:manish.rana2021@vitbhopal.ac.in)
Approach for this project: Will use Deep Learning algorithm and python
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, i want to work on it
Thanks.

**Comment by TAHIR0110** [comment]
@ranamanish674zu what will you make tho?

**Comment by ranamanish674zu** [comment]
> @ranamanish674zu what will you make tho?

i am thinking to make a machine learning and deep learning model....which will be apply on the dataset which will taken from the google form ...actually i worked on this project in my collage epic's project where we collect the data from the google form and apply ml , so i want to apply over there deep learning algorithm which will give some feedback to the user , we simple take the user input from the user and then our model will give some suggetions

**Comment by ranamanish674zu** [comment]
@TAHIR0110 could you please see the isssue
