### ISSUE TITLE
Suicide And Depression Detection based on the Search History

### ISSUE THREAD

**Issue by JyotikaJayani-08** [TAHIR0110/ThereForYou#144]
**Is your feature request related to a problem? Please describe.**
Yes It is related to the problem.
I want to add a complete Deep learning model which will predict suicidal tendencies in a person based on text.

* Describe the solution you'd like :- 
1. I will load the dataset from kaggle.  
2. I will work on dataset using Numpy ,Pandas and other libraries.
3. I will be using keras deep learning API for implementing neural networks. 
4. Model training and evaluation.

* Describe alternatives you've considered :- 
I will also make a python App for backend.

@TAHIR0110   Please assign me this issue under GSSOC'2024 with appropriate level (1/2/3)
expected level : 3

**Comment by TAHIR0110** [comment]
@JyotikaJayani-08 Assigned level3!! but don't just make a model which would predict suicide or depression based on search history, integrating it somewhere would be appreciated.

**Comment by JyotikaJayani-08** [comment]
@TAHIR0110  Got it sir, I will try to integrate in a python app.
