### ISSUE TITLE
Lung Cancer Detection Using Convolutional Neural Network:

### ISSUE THREAD

**Issue by Anshika14528** [TAHIR0110/ThereForYou#164]
Detection of Lung cancer utilizing Convolutional Neural Networks (CNN) with strategically designed convolutional layers, max pooling layers ,dense Layer and fully connected layers in Deep Learning.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by TAHIR0110** [comment]
@Anshika14528 assigned!

**Comment by aryanchauh** [comment]
Hello @TAHIR0110 sir!
Can I work on this issue . I hope u assign me this issue
