### ISSUE TITLE
Cataract Disease detection using Machine learning

### ISSUE THREAD

**Issue by RajKhanke** [TAHIR0110/ThereForYou#174]
**Is your feature request related to a problem? Please describe.**
Cataract is an eye disease (called Motiyabindu in Hindi Language) is a disease frequently seen in old age people frequently as well as in some middle age people. Early remedial measures are necessary to cure it, otherwise human may loss their entire eyes and this may lead to anger and depression. Hence this new project feature involves detecting cataract earlier by simple image or webcam input of eye images . 

**Describe the solution you'd like**
The model will be trained using CNN or YOLO V8 model using given Kaggle dataset on Cataract :

https://www.kaggle.com/datasets/sheemazain/cataract-classification-dataset-in-ds
i will prepare a proper Ipynb notebook using all data science and DL steps, EDA and visualizations and insights

please assign this issue (new feature ) to me as a GSSoc'24 contributor along with Gssoc label and level

**Comment by TAHIR0110** [comment]
@RajKhanke  assigned!
