### ISSUE TITLE
Diabetes Prediction using machine learning:

### ISSUE THREAD

**Issue by Anshika14528** [TAHIR0110/ThereForYou#175]
**Is your feature request related to a problem? Please describe.**

I want to build a model which  can helps us to predict whether a person has diabetes or not with the help of Machine Learning.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by TAHIR0110** [comment]
@Anshika14528 assigned!
