### ISSUE TITLE
Breast Cancer Detection:

### ISSUE THREAD

**Issue by Anshika14528** [TAHIR0110/ThereForYou#176]
**Is your feature request related to a problem? Please describe.**
This project helps us to Detect  Breast Cancer using machine learning with python.

I agree to follow this project's Code of Conduct
I'm a GSSoC'24 contributor
I want to work on this issue

**Comment by TAHIR0110** [comment]
@Anshika14528  assigned!

**Comment by malvika-sinha** [comment]
I wish to work on this. kindly assign this task to me.

**Comment by Kirti-Pant** [comment]
@TAHIR0110  kindly assign this it to me.
