### ISSUE TITLE
💡[Feature]:  Fetal Health Detection using CTG data: ML

### ISSUE THREAD

**Issue by abckhush** [TAHIR0110/ThereForYou#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The model will be trained using 
1. Logistic Regression
2. Decision Tree
3. Random Forest
4. Gradient Boosting 

Using given Kaggle dataset :
https://www.kaggle.com/datasets/andrewmvd/fetal-health-classification/data
I will prepare a proper .ipynb notebook.

Kindly assign this issue to me as a GSSoc'24 contributor.

### Use Case

Cardiotocograms (CTGs) help monitor fetal health through ultrasound, allowing early interventions to save lives, significantly reducing preventable child and maternal deaths.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TAHIR0110** [comment]
@abckhush assigned!
