### ISSUE TITLE
🐞[Bug]: Issue in autocommenting on merged pr

### ISSUE THREAD

**Issue by Anshika14528** [TAHIR0110/ThereForYou#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I checked on the recent merged pr but we are not getting the autocomment feature and i looked more into it and i found this message

### Expected behavior

message should be commented

### Add ScreenShots

<img width="1457" alt="Screenshot 2024-06-19 at 4 14 18 PM" src="https://github.com/TAHIR0110/ThereForYou/assets/168436423/32e7a8c5-323a-4666-b599-6d3e61ce1e67">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@Anshika14528 go ahead.
