### ISSUE TITLE
Person Detection on Railway Tracks for Suicide Prevention

### ISSUE THREAD

**Issue by richardar** [TAHIR0110/ThereForYou#19]
Problem:
In recent years, there has been a concerning rise in railway-related suicides. Detecting individuals on railway tracks in real time to prevent such incidents is a critical challenge. Existing methods often rely on human intervention, which may not always be timely or effective.

Solution:
I propose implementing a feature within the existing railway safety systems to detect individuals on railway tracks using an advanced computer vision algorithm. This feature would analyze live camera feeds along railway tracks and identify human presence, alerting railway authorities or relevant emergency services promptly.

I am gssoc contributor, kindly assign this to me.

**Comment by Hetul16** [comment]
Solution:
To address person detection on railway tracks, we can propose CNN from scratch or we can leverage transfer learning approch with pre-trained models like YOLOv5 or ResNet50, employing OpenCV for robust implementation. Our approach involves training on a curated dataset specific to this project, fine-tuning models for accurate detection. Additionally, integrating an alert mechanism ensures timely notifications to authorities upon detecting individuals on tracks.

Why Me:
With deep expertise in CNNs and computer vision, I am well-suited for this project. My experience encompasses both theoretical understanding and practical application, as demonstrated by presentations and project work. I bring a blend of skills, including model development and insights from research, making me confident in contributing effectively to this endeavor.

**Comment by gratusrichard** [comment]
I've did something similar already, kindly assign this issue to me.

**Comment by TAHIR0110** [comment]
@gratusrichard  assigned!

**Comment by vishuhere** [comment]
Straight to the point: I had understood the problem and will apply the best machine algorithm in it including VITpose and mediapipe. 

I had recently worked on an internship on the object detection and image segmentation part. I'm well in this field.
Currently a GSSOC contributor,kindly assign me this task.

**Comment by TAHIR0110** [comment]
@Hetul16 I have added another issue #23

**Comment by gratusrichard** [comment]
I have created a pull request for this issue. kindly check it out. @TAHIR0110

**Comment by tejaswini4996** [comment]
I would like to work on this issue
