### ISSUE TITLE
💡[Feature]:  Alzheimer Disease Prediction

### ISSUE THREAD

**Issue by AmrutaJayanti** [TAHIR0110/ThereForYou#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to develop a model which predicts accurately alzheimers disease.

### Use Case

Alzheimers is a problem which became common these days . My model is trained on patients data and gives results.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushka-Gosavi** [comment]
@TAHIR0110 
Kindly assign this issue to me.

**Comment by TAHIR0110** [comment]
@AmrutaJayanti assigned!
