### ISSUE TITLE
💡[Feature]: Smiling Detection

### ISSUE THREAD

**Issue by UppuluriKalyani** [TAHIR0110/ThereForYou#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature enables the detection of smiles in facial images using a neural network. It processes the dataset by resizing and normalizing images, then trains the model on labeled data to distinguish between smiling and non-smiling faces. The system includes model evaluation, saving, and loading capabilities for accurate and efficient smile detection

### Use Case

Add this feature to apps like photo albums, social media sites, and marketing tools to automatically find and tag pictures of people smiling. This makes the user experience better and helps deliver more personalized content.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by UppuluriKalyani** [comment]
@TAHIR0110 sir can you please assign this issue to me.

**Comment by TAHIR0110** [comment]
@UppuluriKalyani assigned!
