### ISSUE TITLE
Perform EDA for medical condition predition model

### ISSUE THREAD

**Issue by Kyouma45** [TAHIR0110/ThereForYou#2]
I want to perform EDA on medical condition model. Please assign this task to me. Also, please provide the dataset 'he.csv' used for training.

**Comment by Atharv714** [comment]
Ignore that file, if you want , i could assign you a task to train a NLP model for danger prediction.

**Comment by Kyouma45** [comment]
@Atharv714 I would like to work on NLP model for danger prediction. Please assign this issue to me

**Comment by Atharv714** [comment]
@Kyouma45 we have created a new issue, pls reply there, so that we could assign you the issue
