### ISSUE TITLE
💡[Feature]:  Add asthma detection

### ISSUE THREAD

**Issue by debangi29** [TAHIR0110/ThereForYou#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Can add asthma detection 
This project predicts whether the person is suffering from the respiratory disease of Asthma or not. The porject classifies the person into three main categories as suffering from mild asthma, suffering from Moderate or high asthma and Not suffering from asthma on streamlit based application.projectStreamlit

### Use Case

The project classifies the person into three main categories: suffering from mild asthma, Moderate or high asthma, and Not suffering from asthma on streamlit-based application.

The application takes input like the person has various disorders like tiredness, running nose,nasal congestion, difficulty in breathing or not, age group , gender, and predict the likeliness of the disease

### Benefits

The script will allow you to predict whether the person is suffering from asthma or not based on input features.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@debangi29 go ahead.
