### ISSUE TITLE
Post-Traumatic Stress Disorder Detection

### ISSUE THREAD

**Issue by mahek0620** [TAHIR0110/ThereForYou#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Post-Traumatic Stress Disorder (PTSD) is a mental health condition triggered by experiencing or witnessing a traumatic event. It can manifest in various symptoms such as flashbacks, nightmares, severe anxiety, and uncontrollable thoughts about the event.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TAHIR0110** [comment]
@mahek0620 assigned!
