### ISSUE TITLE
Add Infant Health Prediction

### ISSUE THREAD

**Issue by Khushi-Pushkar** [TAHIR0110/ThereForYou#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Hey @TAHIR0110 @Avdhesh-Varshney . I am a GSSoC'24 Contributor.

I'd like to contribute to your project by adding Infant Health Prediction
Kindly assign this issue to me.

### Suggested Change

,

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar kindly elaborate your idea and working behaviour of model?

**Comment by Khushi-Pushkar** [comment]
We use a synthetic infant health dataset that mimics real data to help researchers develop and test health models and predictions without using actual personal information.
- EDA - Load the dataset
-  Perform Univariate and Multivariate analysis and draw conclusions from there.
 - Explore Correlation Matrix
 - Check the distribution(skewness) of the columns
 - Detect Outliers
 - Detect Class Label Imbalance

**Comment by TAHIR0110** [comment]
@Khushi-Pushkar assigned!
