### ISSUE TITLE
Stroke Prediction

### ISSUE THREAD

**Issue by Khushi-Pushkar** [TAHIR0110/ThereForYou#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Hey @TAHIR0110 @Avdhesh-Varshney . I am a GSSoC'24 Contributor.

I'd like to contribute to your project by adding Stroke Prediction
Kindly assign this issue to me.

### Suggested Change

.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar go ahead.
