### ISSUE TITLE
💡[Feature]: Genetic Disorder detection using a medical dataset that includes a variety of patient information and clinical data.

### ISSUE THREAD

**Issue by debangi29** [TAHIR0110/ThereForYou#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This dataset focusses on pediatric patients, capturing a wide range of information from genetic data to clinical test results and demographic details. It is used for research on genetic disorders, the impact of maternal and paternal health on child health, and other related medical studies
A trained ML model to detect genetic disorder

### Use Case

This machine learning model can significantly improve the detection and management of genetic disorders in pediatric patients. By leveraging comprehensive patient data, the model can provide accurate, timely, and actionable insights to healthcare professionals, ultimately leading to better patient care and outcomes.

### Benefits

The dataset includes comprehensive patient data such as demographic information, clinical test results, family medical history, genetic data, and observed symptoms. Key features include patient age, genes inherited from parents, blood cell counts, heart and respiratory rates, and detailed information on genetic disorders and their subclasses.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by debangi29** [comment]
Please assign this issue to me :) @Avdhesh-Varshney @TAHIR0110

**Comment by Avdhesh-Varshney** [comment]
@debangi29 go ahead.
