### ISSUE TITLE
💡[Feature]: Face Mask Detection

### ISSUE THREAD

**Issue by UppuluriKalyani** [TAHIR0110/ThereForYou#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Build a model that detects whether a person is wearing a face mask or not

### Use Case

Public health monitoring, automated entry systems in offices or public places.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by UppuluriKalyani** [comment]
@TAHIR0110 sir can you please assign this issue to me.

**Comment by UppuluriKalyani** [comment]
@Avdhesh-Varshney sir can you please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@UppuluriKalyani go ahead.
