### ISSUE TITLE
💡[Feature]: Metabolic Syndrome 

### ISSUE THREAD

**Issue by Khushi-Pushkar** [TAHIR0110/ThereForYou#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add Metabolic Syndrome Dataset.

### Use Case

The Metabolic Syndrome Dataset provides valuable insights into individuals diagnosed with metabolic syndrome, a condition linked to increased risk of cardiovascular diseases and type 2 diabetes .Research and Analysis.

### Benefits

The Metabolic Syndrome Dataset serves as a valuable resource for both research and practical applications in healthcare and public health, aiming to improve outcomes and reduce the burden of metabolic disorders globally.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khushi-Pushkar** [comment]
Hi @TAHIR0110 @Avdhesh-Varshney 
please assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar go ahead.
