### ISSUE TITLE
💡[Feature]: Improving-Chronic-Kidney-Disease-Prediction-using-ANN-with-Normalization 

### ISSUE THREAD

**Issue by pavitraag** [TAHIR0110/ThereForYou#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This work aims to accurately predict Chronic Kidney Disease (CKD) using a robust Artificial Neural Network model and compares its performance to various machine learning algorithms, ultimately achieving an impressive accuracy of 98%, making it a promising tool for CKD diagnosis.

### Use Case

for finding kidney disease with most accuracy.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pavitraag** [comment]
hey @TAHIR0110 can u please assign me this

**Comment by pavitraag** [comment]
@TAHIR0110 can you please assign me this under gssoc

**Comment by TAHIR0110** [comment]
@pavitraag assigned!
