### ISSUE TITLE
💡[Feature]: Endometrial cancer Prediction

### ISSUE THREAD

**Issue by Khushi-Pushkar** [TAHIR0110/ThereForYou#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi @TAHIR0110 @Atharv714 
I want to add Endometrial Cancer Prediction.

Endometrial cancer, which originates in the lining of the uterus, is the most common gynecologic cancer. Early detection is crucial for successful treatment and improving survival rates.

### Use Case

.

### Benefits

Early Detection

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khushi-Pushkar** [comment]
@TAHIR0110  @Avdhesh-Varshney sir, please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@Khushi-Pushkar show me the dataset which you will be using?

**Comment by Khushi-Pushkar** [comment]
https://www.kaggle.com/datasets/yeganehbavafa/uterine-corpus-endometrial-carcinoma

**Comment by Khushi-Pushkar** [comment]
Please assign this issue to me @TAHIR0110 @Atharv714
