### ISSUE TITLE
💡[Feature]: Celebrities Face Recognition

### ISSUE THREAD

**Issue by UppuluriKalyani** [TAHIR0110/ThereForYou#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Train a model to recognize various celebrities from images.

### Use Case

Media and entertainment industry, social media platforms, event management.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by UppuluriKalyani** [comment]
@TAHIR0110 @Avdhesh-Varshney sir, please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@UppuluriKalyani go ahead.
