### ISSUE TITLE
💡[Feature]: Suicide and Depression Detection

### ISSUE THREAD

**Issue by abckhush** [TAHIR0110/ThereForYou#250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

https://www.kaggle.com/datasets/nikhileswarkomati/suicide-watch/data
Models that will be implemented:
1. LSTM
2. BiLSTM

### Use Case

 To detect suicide and depression in a text.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abckhush** [comment]
@TAHIR0110 kindly assign me this issue.

**Comment by abckhush** [comment]
@Avdhesh-Varshney Kindly assign me the issue.

**Comment by Avdhesh-Varshney** [comment]
@abckhush go ahead.
