### ISSUE TITLE
💡[Feature]:  Maternal Health risk prediction using Machine learning

### ISSUE THREAD

**Issue by RajKhanke** [TAHIR0110/ThereForYou#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Objective:
To develop a predictive model and a web application that can classify the risk level (high, medium, low) for pregnant women based on various health parameters. The project will involve data analysis, preprocessing, feature engineering, model training, evaluation, and deployment using a Streamlit web application.

Dataset:
The dataset obtained from Kaggle includes the following columns:

https://www.kaggle.com/datasets/pyuxbhatt/maternal-health-risk?select=Maternal+Health+Risk+Data+Set.csv

Age: Age of the pregnant woman
SystolicBP: Systolic blood pressure
DiastolicBP: Diastolic blood pressure
BS: Blood sugar level
BodyTemp: Body temperature
HeartRate: Heart rate
RiskLevel: Risk level classification (high risk, medium risk, low risk)

Steps Involved:

1) Data Analysis:

Exploratory Data Analysis (EDA):
Understand the distribution of each feature.
Identify any patterns or trends in the data.
Detect outliers and anomalies.
Visualize relationships between features and the target variable (RiskLevel).

2) Data Preprocessing:

Handling Missing Values:
Identify and handle missing data through imputation or removal.
Data Transformation:
Normalize or standardize numerical features.
Encode categorical variables if any.
Feature Selection:
Select relevant features that contribute most to the prediction.

3) Feature Engineering:

Creating New Features:
Derive new features that might help in improving the model's performance.
Feature Scaling:
Apply scaling techniques like Min-Max scaling or Standard scaling to bring all features to a similar range.

4)Model Training

5) Model Deployment

Integrate the trained model with the Streamlit app.

### Use Case

The Maternal Health Risk Prediction model can be used by healthcare providers in prenatal care facilities to assess the risk levels of pregnant women during routine check-ups. By inputting patient data such as age, blood pressure, blood sugar levels, body temperature, and heart rate into the Streamlit web application, healthcare professionals can quickly determine whether a pregnant woman is at high, medium, or low risk of complications. This real-time risk assessment tool can guide doctors in making timely and informed decisions about additional tests, treatments, or interventions to ensure the well-being of both the mother and the baby.

### Benefits

Implementing this predictive model and web application can significantly enhance prenatal care by providing early warnings of potential health risks. It enables proactive management of maternal health, reduces the likelihood of severe complications, and improves overall pregnancy outcomes. Healthcare providers can allocate resources more effectively, prioritize high-risk cases, and offer personalized care plans. Additionally, the ease of use and accessibility of the Streamlit app ensure that even facilities with limited technical infrastructure can benefit from advanced predictive analytics, ultimately leading to better maternal and fetal health.

### Add ScreenShots

none

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RajKhanke** [comment]
@TAHIR0110 ?

**Comment by Avdhesh-Varshney** [comment]
@RajKhanke go ahead.
