### ISSUE TITLE
💡[Feature]:  HEART DISEASE DETECTION

### ISSUE THREAD

**Issue by ananyag309** [TAHIR0110/ThereForYou#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This project aims to compare the performance of a convolutional neural network (CNN) implemented using TensorFlow/Keras with that of a Random Forest classifier for binary classification tasks.

### Use Case

The dataset is collected from the following link : https://www.kaggle.com/datasets/andrewmvd/heart-failure-clinical-data

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ananyag309** [comment]
@TAHIR0110 @Atharv714 sir please assign this issue to me under gssoc

**Comment by ananyag309** [comment]
@TAHIR0110 @Atharv714 @Avdhesh-Varshney sir please assign this issue to me under gssoc

**Comment by Avdhesh-Varshney** [comment]
@ananyag309 go ahead.
