### ISSUE TITLE
💡[Feature]: Suicide and Depression Detection

### ISSUE THREAD

**Issue by sreevidya-16** [TAHIR0110/ThereForYou#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The dataset is a collection of posts from the "SuicideWatch" and "depression" subreddits on the Reddit platform. The posts were collected using the Pushshift API, covering all posts made to "SuicideWatch" from December 16, 2008 (creation) to January 2, 2021, and "depression" posts from January 1, 2009, to January 2, 2021. All posts from "SuicideWatch" are labeled as suicide, while posts from the depression subreddit are labeled as depression. Non-suicide posts were collected from the "teenagers" subreddit.

The dataset used in this project is: https://www.kaggle.com/datasets/nikhileswarkomati/suicide-watch/data

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ritzzcodes** [comment]
please assign this task to me.

**Comment by sreevidya-16** [comment]
@TAHIR0110 @Atharv714 @Avdhesh-Varshney sir please assign this issue to me under gssoc
