### ISSUE TITLE
💡[Feature]: Medical Charges for Smokers and Non-smoker

### ISSUE THREAD

**Issue by pavitraag** [TAHIR0110/ThereForYou#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This Data analysis and data visualization project consists of the fact that the average medicine charges can be changed for the smokers and non-smokers.

Algorithms Used for predicting the average medical charges for the smokers :
-Linear Regression
-Polynomial Regression of 2nd degree
-Lasso Regression
-Ridge Regression
-SVM or, Support Vector Machine
-Random Forest Regression
-Decision tree regression

### Use Case

to find the average medicine charges can be changed for the smokers and non-smokers.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pavitraag** [comment]
[insurance.csv](https://github.com/user-attachments/files/16310773/insurance.csv)
This is the data

**Comment by TAHIR0110** [comment]
@pavitraag assigned!!
