### ISSUE TITLE
💡[Feature]: Blood Cell Cancer Detection with CNN and EfficientNetB3

### ISSUE THREAD

**Issue by navyabijoy** [TAHIR0110/ThereForYou#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Using CNN to detect the presence of blood cell cancer from the images dataset uploaded on kaggle.

### Use Case

Will help in detection of blood cell cancer.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TAHIR0110** [comment]
@navyabijoy assigned!

**Comment by sreevidya-16** [comment]
No update on this issue since a week
So @TAHIR0110, can I work on this issue ?

**Comment by navyabijoy** [comment]
@sreevidya-16 i am going to work on it this weekend. the pr will be created by tomorrow.
