### ISSUE TITLE
💡[Feature]: Add Maternal Health Risk Prediction

### ISSUE THREAD

**Issue by kosuri-indu** [TAHIR0110/ThereForYou#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add the maternal health risk prediction model

The dataset contains: 
- Age: Age of pregnant women.
- SystolicBP: Upper value of Blood Pressure in mmHg
- DiastolicBP: Lower value of Blood Pressure in mmHg
- BS: Blood glucose levels in mmol/L.
- HeartRate: Heart rate in beats per minute.
- Risk Level: Predicted Risk Intensity Level during pregnancy.

Built the prediction model using various machine learning model
- KNN
- Random Forest
- Support Vector Machine
- Decision Tree Classifier
- XG Boost
Used GridSearchCV for hyperparameter tuning

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kosuri-indu** [comment]
@TAHIR0110 
Please assign this issue to me :)
Thank you

**Comment by RajKhanke** [comment]
@kosuri-indu this issue is already  assigned to me #262 , you may try a different one .
