### ISSUE TITLE
GREETING ON ARRIVAL

### ISSUE THREAD

**Issue by aditikhare16** [TAHIR0110/ThereForYou#54]
**Is your feature request related to a problem? Please describe.**
It can work as a sweet and warm greeting to the user.

**Describe the solution you'd like**
When the user opens this page, a prompt can come up "Hey, hope you are having a good day! How are you feeling today?" Followed by emojis with "bad...fine...good...very good".
Based on the selection of the user, a message or some suggestion would come up.
eg, if the user chooses "very good" the message would come up "yaay! keep up with that energy!"

**Describe alternatives you've considered**
none.

**Additional context**
Something just like this.
![image](https://github.com/TAHIR0110/ThereForYou/assets/114524718/80aa79d7-4fd1-4a88-84b7-ef48824a6edb)
![image](https://github.com/TAHIR0110/ThereForYou/assets/114524718/52d1e5e6-b68d-4b5c-a13d-eecac54059ce)
![image](https://github.com/TAHIR0110/ThereForYou/assets/114524718/77c67419-8c28-41ba-8101-a3e2fffd331a)

Please assign me this feature under GGSOC'24.

**Comment by Janvibaghel** [comment]
his @aditikhare16 mam, I'm also interested in this issue . Kindly please assign this issue to me .

**Comment by aditikhare16** [comment]
> his @aditikhare16 mam, I'm also interested in this issue . Kindly please assign this issue to me .

Hey, I'm not the project admin.
I raised this feature and myself have requested @TAHIR0110 to assign me this issue 😊

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by aditikhare16** [comment]
Please assign me this feature is you like it @TAHIR0110

**Comment by aditikhare16** [comment]
I have worked on this and developed the feature as well. Please assign this to me.

**Comment by aditikhare16** [comment]
This would pop up on opening the website and will work as a warm welcome. Please assign me this!
https://github.com/TAHIR0110/ThereForYou/assets/114524718/48a6381a-c5e4-4d30-929a-f9627fa92196
