### ISSUE TITLE
GSSoC'24: OCR Detection (Image to Text)

### ISSUE THREAD

**Issue by SAM-DEV007** [TAHIR0110/ThereForYou#56]
**Is your feature request related to a problem? Please describe.**
A feature which enhances the functionality of the predictions of danger, or suicidal thoughts. When the victim is in danger and is unable to speak at the moment, a text can be displayed to the camera which can predict the outcomes and notify the nearby users accordingly. For suicide predictions, it is helpful in the situation where the victim is writing the death note, so that the camera may get a glimpse of the note, and via the predictions of the model, it can infer the outcomes.

**Describe the solution you'd like**
The sole purpose is to provide functionality for image to text conversion. For visualization, the frame will have the detected text surrounded with bounding boxes with the text detected and the confidence, if the latter surpasses a certain threshold. A pretrained model from `easyocr` will be used along with `cv2`.

**Use Case**
The extracted text can be used with the existing models in the repository that takes text as their primary input for various predictions.

Please assign it to me under GSSoC'24.

**Comment by TAHIR0110** [comment]
The use case you've described raises an important point. If a person is capable of opening the camera, they might also be able to directly access an SOS button or emergency feature. In such cases, direct access to emergency features would likely be more efficient and reliable than relying on image-to-text conversion to predict danger. However, there might be some cases where this would be useful therefore I will still assign this issue.

**Comment by SAM-DEV007** [comment]
@TAHIR0110 A pull request has been created. I didn't expect it to be done with it that quick.

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up under GSSoC'24. Lemme know. :)
