### ISSUE TITLE
Music recommendation feature

### ISSUE THREAD

**Issue by sdp2004** [TAHIR0110/ThereForYou#67]
Detecting the facial features and voiceovers of a person try to recommend them the music which can help them to come out from their depression. Also use music therapy in a daily treatment like basis to treat different psychiatric problems.

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by sdp2004** [comment]
Hello. I am also a gssoc contributor. And it will be my pleasure to work
with you on this issue together.

**Comment by TAHIR0110** [comment]
@sdp2004 and @varshithar12 I have assigned this issue to both of you!

**Comment by sdp2004** [comment]
Got it, thank you.

**Comment by KhushiNyati** [comment]
I want to work on this issue. 
Please assign me this issue

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up under GSSoC'24. Lemme know. :)

**Comment by sdp2004** [comment]
I have uploaded the solution pls accept my pull request and merge it to the main repository
