### ISSUE TITLE
Add Forking Steps for New contributors in README file 

### ISSUE THREAD

**Issue by amroodh** [TAHIR0110/ThereForYou#75]
Greeting PA,
The current README.md required forking steps for new contributors.
kindly assign me this issue under GSSOC 24
Thank you.

**Comment by officialhemant511** [comment]
hi @TAHIR0110  can u pls assign this issue to me under gssoc

**Comment by AyushSinghRajput1366** [comment]
hi @TAHIR0110  can u pls assign this issue to me under gssoc
