### ISSUE TITLE
Develop an AI-Driven Diagnostic System

### ISSUE THREAD

**Issue by TAHIR0110** [TAHIR0110/ThereForYou#78]
Develop an AI-driven diagnostic system to analyze medical data and provide accurate, real-time assessments. The task involves creating algorithms to detect patterns, predict diseases, and recommend treatments, enhancing the efficiency and precision of healthcare diagnostics.

I need this before 22 may.

Hence I will assign this as a level 3 label, due to its deadline.

**Comment by Kyouma45** [comment]
Sir, I have experience in building these kinds of models. Please assign this issue to me.
Also, can you please give a sample input or the dataset?
Thank you

**Comment by TAHIR0110** [comment]
@Kyouma45 I don't have a dataset currently I would appreciate if you find some dataset on kaggle or NIH.
Patient Information:

We would prefer the model should predict age, gender(there is already a model in my repository), weight(could be user input), height(could be user input), Medical History(User Input), Symptoms(User Input). and hence it would predict Electrocardiogram, Cholesterol levels and would recommend prescriptions including medicines(if possible).

Age: 35
Sex: Male
Weight: 85 kg (187 lbs)
Height: 1.78 m (5'10")
Medical History: Hypertension (diagnosed 2 years ago)

Symptoms:

Chest pain (described as sharp, squeezing pain in the center of the chest)
Shortness of breath (started yesterday)
Nausea and vomiting
Test Results:

Blood pressure: 160/100 mmHg
Electrocardiogram (ECG): Abnormal T-wave inversions
Cholesterol levels: LDL - 190 mg/dL, HDL - 40 mg/dL

If you need any further assistance feel free to ask.

**Comment by Kyouma45** [comment]
> @Kyouma45 I don't have a dataset currently I would appreciate if you find some dataset on kaggle or NIH.
> 
> We would prefer the model should predict age, gender(there is already a model in my repository), weight(could be user input), height(could be user input), Medical History(User Input), Symptoms(User Input). and hence it would predict Electrocardiogram, Cholesterol levels and would recommend prescriptions including medicines(if possible).
> 
> Patient Information:
> 
> Age: 35
> Sex: Male
> Weight: 85 kg (187 lbs)
> Height: 1.78 m (5'10")
> Medical History: Hypertension (diagnosed 2 years ago)
> 
> Symptoms:
> 
> Chest pain (described as sharp, squeezing pain in the center of the chest)
> Shortness of breath (started yesterday)
> Nausea and vomiting
> 
> Test Results:
> 
> Blood pressure: 160/100 mmHg
> Electrocardiogram (ECG): Abnormal T-wave inversions
> Cholesterol levels: LDL - 190 mg/dL, HDL - 40 mg/dL
> 
> If you need any further assistance feel free to ask.
> 

Understood, I would love to give it a try. Please assign this issue to me

**Comment by TAHIR0110** [comment]
@Kyouma45 assigned!

**Comment by Divyanshi-2211** [comment]
Could you please assigned it to me as well?

**Comment by Kushagra22Singh** [comment]
Hey @TAHIR0110, 
I would like to work on these issues and get it resolved. As the dataset is not available so its better to generate a synthetic data or scrape the data from various sites. I've been working on the data science part which would put me on a leverage on these. Please assign me to this issue.

**Comment by TAHIR0110** [comment]
@Kushagra22Singh I will assign you as a contributor as well, but do check the deadline once.

**Comment by Kyouma45** [comment]
Sir @TAHIR0110, I have finished working on the model and have created a pull request. Please review it.

**Comment by Kyouma45** [comment]
@TAHIR0110 sir, please add GSSOC and level labels to my PR.
