### ISSUE TITLE
Girlscript Summer of Code Introduction/Tracking

### ISSUE THREAD

**Issue by Princegupta101** [TAHIR0110/ThereForYou#9]
👋 Hi @TAHIR0110,

I am Prince,web developer(Core Team) Girlscript Summer of Code. I'll be collaborating with you on preparing your repo for GSSoC'24 Program

Why are these changes required?
After Analysing last year's contributions and feedback it would be great for students to have a couple of standard readme files on the repo to understand what the project is all about and some issues detailing what they can contribute. This will help you to see increased engagement in your repository as well.

As mentioned students get a chance to learn step by step, how to build this project as well as invite mentors to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for Girlscript summer of code 2024 on 10th May.

This issue will serve as a tracking issue to track all issues related to GSSoC'24. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8

**Comment by sakshi-sonii** [comment]
Hello, I hope this message finds you well. I am well experienced in python with 5 stars in hackerrank and consistently learning ML. I want to gain hands on experience by contributing to this project through GSSOC'24. Please give me opportunity to contribute to this project. I hold a google data analytics course certificate of 6 months too. I have already completed a project named AI avatar generation in which I have already worked with sound using the librosa library and lipsync GANs. I have a deep knowledge of python,its libraries and frameworks. Please let me contribute to this isuue.

**Comment by KhushAgrawal001** [comment]
Greetings
This is Khush agrawal
i would like to work on this issue as a part of this year's GSSoC So please assign this issue to me
